### ISSUE TITLE
Sort audits column by most recent audit

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/blockchainSecurityDB#20]
Sorting by the 'Audits' column would be more useful if it sorted by the date of the most recent audit. This would help see which projects are most proactive in assessing the security of their systems and processes. 

This screenshot shows sorting in the audits column, which is done alphabetically. Since the first part of the name of the audit is usually the same as the project, this is not super helpful.

![image](https://user-images.githubusercontent.com/23033765/86275106-bf7ca580-bba0-11ea-938a-c1234b1108cf.png)

**Comment by kadenzipfel** [comment]
It actually is sorting projects by audit dates, but it could probably be refined. Currently, it just sorts by the year of the most recent audit, but since so many projects have audits on the same years, the sorting isn't always consistent. I could improve this by sorting by the year *and* month. 

It's also confusing because the individual audits listed for a project are also not in any order, so maybe it's worth having project audits be automatically sorted by year when the markdown is generated.

**Comment by maurelian** [comment]
> so maybe it's worth having project audits be automatically sorted by year when the markdown is generated.

Yes, that would also be great!

**Comment by kadenzipfel** [comment]
All set!

**Comment by maurelian** [comment]
Could it also show the most recent audit at the top of the list for each project? 
![image](https://user-images.githubusercontent.com/23033765/86401346-0d181180-bc78-11ea-938b-0c6aaf6d3b5a.png)

**Comment by kadenzipfel** [comment]
> Could it also show the most recent audit at the top of the list for each project?

It's possible, but it would be quite difficult. I imagine it would take between 4-8 hours to setup, so not sure it's worth the time to complete. What do you think?
